In [ ]:
import pandas as pd
import numpy as np

set some constant variables

In [ ]:
STOCK_PRICE_MAX = 100
NOISE_SCALE = 5

created a list of companies and then created a data dictionary that designated an integer value for each of my companies
- did this so that I can run them numbers through my design matrix


In [ ]:
Company = ['Apple', 'Tesla', 'Microsoft', 'Amazon', 'Avronna', 'Novartis', 'Merck', 'Shell', 'Exxon', 'Chevron']
co_map = {x:ii for (ii,x) in enumerate(Company)}
print(co_map)

{'Apple': 0, 'Tesla': 1, 'Microsoft': 2, 'Amazon': 3, 'Avronna': 4, 'Novartis': 5, 'Merck': 6, 'Shell': 7, 'Exxon': 8, 'Chevron': 9}


- created an empty list and called it acc
- for a range of years, we will select one company per each year
- selected co will be 1 non selected co for that year will remain 0

In [ ]:
acc = []

for yy in range(2008, 2008+5):
  for c in Company:
    new_row = np.zeros((len(Company), ))
    new_row[co_map[c]] = 1
    acc.append(new_row)

np.vstack will stack our arrays we've just written vertically
- basically, with our for loop, within the range of years we selected (number of times we want to reiterate through each company) we ran another for loop that iterates through each company in our comapny list
- first our company we create a list of 0s the length of the number of companies in our list
- then when we reach the company we currently are iterating through, we set it = to 1
- we append that row to our empty list 'acc' and then go to the next company in the same year
- once we iterate through all teh companies we move on to the next year and do the same

In [ ]:
design = np.vstack(acc)

We should expect, for 10 companies over 5 years, that we get an array that has 50 rows and 10 columns
- our number of columns was set to a length equalling the number of companies, since after we iterate through 10 companies in 1 year we then move on to the next and go through the 10 companies again
- since we iterate through 10 companies 5 times, we should end up with 50 rows, 5 years of data for each of our 10 companies

In [ ]:
design

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 

In [ ]:
# check shape of design just to mkae sure

design.shape

(50, 10)

In [ ]:
# Now we want to create our coefficients (weights)
# This is how our predictor variables will relate to our result variables

# multiplied it by stock price max so we could get some more realistic values between 0 and 100

# fake_weights = np.random.rand(design.shape[1]) * STOCK_PRICE_MAX
fake_weights = np.random.rand(design.shape[1])

In [ ]:
# What are our fake weights? Why did we get these weights?
# where did they come from? How were they generated?

fake_weights

array([0.871541  , 0.34441759, 0.15363514, 0.1731213 , 0.32763612,
       0.73831332, 0.63808943, 0.28086607, 0.26851483, 0.60566187])

In [ ]:
# Now we take the dot product of our design matrix by our fake_weights
# to give the predicted values of our response var for each observations

fake_outcomes = np.dot(design, fake_weights)

In [ ]:
# Generating random data for me to predict
# Right now the data is generated from 0-1. In order to make the data
  # more symmetrical we subtract .5 so it goes from -.5 to .5

# The noise is our error term, increasing variance and unpredictability

#fake_outcomes += (np.random.rand(fake_outcomes.shape[0]) - 0.5 ) * NOISE_SCALE
fake_outcomes += np.random.rand(fake_outcomes.shape[0])

In [ ]:
np.random.rand(fake_outcomes.shape[0])

array([0.19859266, 0.5150527 , 0.98332965, 0.7379807 , 0.63105576,
       0.02657087, 0.68653711, 0.70411922, 0.89235242, 0.05526386,
       0.58320097, 0.38576394, 0.08636625, 0.81917706, 0.09762182,
       0.95914968, 0.45286714, 0.24547549, 0.37411185, 0.12480933,
       0.76599087, 0.28228689, 0.67771257, 0.16779706, 0.9396888 ,
       0.63117767, 0.73996543, 0.24786669, 0.9090902 , 0.16137201,
       0.14982038, 0.82276746, 0.80300912, 0.9167623 , 0.5605077 ,
       0.58763867, 0.71882174, 0.60330352, 0.41259153, 0.48246492,
       0.82528299, 0.73218751, 0.6167658 , 0.35603778, 0.3105943 ,
       0.04969164, 0.98485042, 0.67397698, 0.55215522, 0.94468027])

In [ ]:
fake_outcomes

array([1.06794478, 0.77117301, 0.5115711 , 0.50966574, 0.88179329,
       0.89499196, 1.07251027, 1.20712846, 0.37515877, 1.23727669,
       1.41002586, 1.29794504, 0.9075199 , 0.71375696, 1.02744744,
       0.80723865, 1.60205628, 0.98551508, 0.77260352, 0.62729513,
       1.0461248 , 0.50271316, 0.97883457, 1.0189272 , 0.49102653,
       1.37416177, 1.317333  , 1.23116202, 0.46226756, 1.4800565 ,
       0.93851475, 0.91114169, 0.81240543, 0.89040398, 1.01660218,
       1.72538414, 1.12269434, 0.81018231, 1.10388507, 1.15306342,
       1.84797823, 0.88554723, 0.30599413, 0.91722807, 0.8757749 ,
       1.11155942, 0.76162358, 1.08321576, 1.17971606, 0.79698184])

In [ ]:
# this gives us the fake outcome for every tenth value in our matrix (Apple||0)

fake_outcomes[::len(Company)]

array([1.06794478, 1.41002586, 1.0461248 , 0.93851475, 1.84797823])

In [ ]:
# What is the average of the predicted values for y when company is Apple?

np.mean(fake_outcomes[::len(Company)])

1.2621176844139292

Using linear reg library for now but will do it manually later

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
mylr = LinearRegression()

In [ ]:
mylr.fit(design, fake_outcomes)

LinearRegression()

In [ ]:
fake_outcomes.shape

(50,)

In [ ]:
 mylr.coef_

array([ 0.28545525, -0.10295841, -0.2733974 , -0.16666604, -0.11813357,
        0.20600476,  0.19858106,  0.0867783 , -0.19793623,  0.08227228])

In [ ]:
mylr.intercept_

0.9766624317603677

In [ ]:
mylr.coef_ + mylr.intercept_

array([1.26211768, 0.87370403, 0.70326503, 0.80999639, 0.85852886,
       1.18266719, 1.1752435 , 1.06344073, 0.7787262 , 1.05893471])

What we just did:
- we had repeated obs for each company a number of times
- we perfectly modeled the world as something evident
- there was only one factor called company, no random noise
- what linear regression does is subtract average value of outcome and fits intercept to that
- intercept is something that takes care of how much do i get for free?

In [ ]:
mylr = LinearRegression(fit_intercept=False)

mylr.fit(design, fake_outcomes)

mylr.coef_

array([1.26211768, 0.87370403, 0.70326503, 0.80999639, 0.85852886,
       1.18266719, 1.1752435 , 1.06344073, 0.7787262 , 1.05893471])

Interecept is 0 because we said dont fit it
- dont fit int means dont pretend you get values for free


In [ ]:
mylr.coef_ - fake_weights

array([0.39057668, 0.52928644, 0.54962989, 0.63687509, 0.53089274,
       0.44435387, 0.53715407, 0.78257466, 0.51021137, 0.45327284])

In [ ]:
fake_outcomes.reshape(5, len(Company))

array([[1.06794478, 0.77117301, 0.5115711 , 0.50966574, 0.88179329,
        0.89499196, 1.07251027, 1.20712846, 0.37515877, 1.23727669],
       [1.41002586, 1.29794504, 0.9075199 , 0.71375696, 1.02744744,
        0.80723865, 1.60205628, 0.98551508, 0.77260352, 0.62729513],
       [1.0461248 , 0.50271316, 0.97883457, 1.0189272 , 0.49102653,
        1.37416177, 1.317333  , 1.23116202, 0.46226756, 1.4800565 ],
       [0.93851475, 0.91114169, 0.81240543, 0.89040398, 1.01660218,
        1.72538414, 1.12269434, 0.81018231, 1.10388507, 1.15306342],
       [1.84797823, 0.88554723, 0.30599413, 0.91722807, 0.8757749 ,
        1.11155942, 0.76162358, 1.08321576, 1.17971606, 0.79698184]])

In [ ]:
np.mean(fake_outcomes.reshape(5, len(Company)), axis = 0)

array([1.26211768, 0.87370403, 0.70326503, 0.80999639, 0.85852886,
       1.18266719, 1.1752435 , 1.06344073, 0.7787262 , 1.05893471])

Why are these numbers the same as my linear regression coef?

Next: we will make copy of this and add a year factor
- years will be shared for everyone (2008 is same 2008 for everyone)